sonar_preview:
  stage: test
  script:
    - sonar-scanner -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID
  except:
    - master
  tags:
    - sonar

sonar_analyze:
  stage: test
  script:
    - sonar-scanner
  only:
    - master
  tags:
    - sonar